name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Amusement Park
          required: false
        - label: Coral
          required: false
        - label: Bridge
          required: false
        - label: Elevator
          required: false
        - label: Cityscape
          required: false
        - label: Wave
          required: false
        - label: Gazebo
          required: false
        - label: Crosswalk
          required: false
        - label: Swamp
          required: false
        - label: Tunnel
          required: false
