name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Street
          required: false
        - label: Colosseum
          required: false
        - label: Square
          required: false
        - label: Field
          required: false
        - label: Aquarium
          required: false
        - label: Swamp
          required: false
        - label: Reef
          required: false
        - label: Court
          required: false
        - label: Castle
          required: false
        - label: Escalator
          required: false
