name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Church
          required: false
        - label: Tunnel
          required: false
        - label: Pagoda
          required: false
        - label: Canyon
          required: false
        - label: Courtyard
          required: false
        - label: Savannah
          required: false
        - label: House
          required: false
        - label: Road
          required: false
        - label: Aquarium
          required: false
        - label: Cityscape
          required: false
