name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Underpass
          required: false
        - label: Temple
          required: false
        - label: Field
          required: false
        - label: Basin
          required: false
        - label: Causeway
          required: false
        - label: Elevator
          required: false
        - label: Creek
          required: false
        - label: Veranda
          required: false
        - label: Wharf
          required: false
        - label: Plane
          required: false
