name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Island
          required: false
        - label: Amusement Park
          required: false
        - label: Crosswalk
          required: false
        - label: Thoroughfare
          required: false
        - label: Garden
          required: false
        - label: Mosque
          required: false
        - label: Geyser
          required: false
        - label: Field
          required: false
        - label: Wharf
          required: false
        - label: Alley
          required: false
