name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Prairie
          required: false
        - label: Cloud
          required: false
        - label: Arena
          required: false
        - label: Palace
          required: false
        - label: Pagoda
          required: false
        - label: Bicycle
          required: false
        - label: Deck
          required: false
        - label: Street
          required: false
        - label: Plain
          required: false
        - label: Labyrinth
          required: false
