name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Watermill
          required: false
        - label: Plane
          required: false
        - label: Bridge
          required: false
        - label: Underpass
          required: false
        - label: Square
          required: false
        - label: Rainforest
          required: false
        - label: Prairie
          required: false
        - label: Synagogue
          required: false
        - label: Church
          required: false
        - label: River
          required: false
