name: Transform the image (easy)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Gazebo
          required: false
        - label: Lake
          required: false
        - label: Volcano
          required: false
        - label: Bird
          required: false
        - label: Jungle
          required: false
        - label: Alcove
          required: false
        - label: Deck
          required: false
        - label: Ocean
          required: false
        - label: Creek
          required: false
        - label: Vineyard
          required: false
