name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Monument
          required: false
        - label: Star
          required: false
        - label: Savannah
          required: false
        - label: Square
          required: false
        - label: Tree
          required: false
        - label: Meadow
          required: false
        - label: Lagoon
          required: false
        - label: Jungle
          required: false
        - label: Alley
          required: false
        - label: Volcano
          required: false
