name: Transform the image
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    options:
      - label: Balloon
        required: false
      - label:  Cloud
        required: false
      - label:  Tree
        required: false
      - label:  River
        required: false
      - label:  Mountain
        required: false
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
    options:
      - label: Balloon
        required: false
      - label:  Cloud
        required: false
      - label:  Tree
        required: false
      - label:  River
        required: false
      - label:  Mountain
        required: false
      label: Choose multiple
      label: Choose multiple
