name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Ship
          required: false
        - label: Underpass
          required: false
        - label: Prairie
          required: false
        - label: House
          required: false
        - label: Tower
          required: false
        - label: Thoroughfare
          required: false
        - label: Tundra
          required: false
        - label: Monument
          required: false
        - label: Synagogue
          required: false
        - label: Garden
          required: false
