name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Butterfly
          required: false
        - label: Dock
          required: false
        - label: Fountain
          required: false
        - label: Crossroads
          required: false
        - label: Boulevard
          required: false
        - label: Tunnel
          required: false
        - label: Canyon
          required: false
        - label: Aquarium
          required: false
        - label: Garden
          required: false
        - label: Bluff
          required: false
