name: Transform the image (easy)
title: Game easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Swamp
          required: false
        - label: Porch
          required: false
        - label: Escalator
          required: false
        - label: Tundra
          required: false
        - label: Bicycle
          required: false
        - label: Monument
          required: false
        - label: Jungle
          required: false
        - label: Boulevard
          required: false
        - label: Monastery
          required: false
        - label: Colosseum
          required: false
