name: Transform the image (easy)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: this
          required: false
        - label: can
          required: false
        - label: if
          required: false
        - label: so
          required: false
        - label: data
          required: false
        - label: is
          required: false
        - label: see
          required: false
        - label: it
          required: false
        - label: we
          required: false
        - label: works
          required: false
