name: Transform the image (easy)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Cottage
          required: false
        - label: Colosseum
          required: false
        - label: Prairie
          required: false
        - label: Iceberg
          required: false
        - label: Terrace
          required: false
        - label: Jungle
          required: false
        - label: Lane
          required: false
        - label: Bridge
          required: false
        - label: Aqueduct
          required: false
        - label: Labyrinth
          required: false
