name: Transform the image
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:

  - type: checkboxes
    id: multi-selection
    options:
      - label: Balloon
        required: false
      - label:  Cloud
        required: false
      - label:  Tree
        required: false
      - label:  River
        required: false
      - label:  Mountain
        required: false
    attributes:
      label: Choose multiple
          required: false
        - label: Blue sky
          required: false
        - label: Clouds
          required: false
