name: Transform the image (easy)
title: Transform easy - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Bridge
          required: false
        - label: Factory
          required: false
        - label: Fireplace
          required: false
        - label: Crosswalk
          required: false
        - label: Butterfly
          required: false
        - label: Amusement Park
          required: false
        - label: Plain
          required: false
        - label: Pagoda
          required: false
        - label: Tunnel
          required: false
        - label: Thoroughfare
          required: false
