name: Transform the image (easy)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Crosswalk
          required: false
        - label: Creek
          required: false
        - label: Factory
          required: false
        - label: Grove
          required: false
        - label: Castle
          required: false
        - label: Monastery
          required: false
        - label: Fortress
          required: false
        - label: Archipelago
          required: false
        - label: Court
          required: false
        - label: Wave
          required: false
