name: Transform the image (hard)
title: Game hard - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Street
          required: false
        - label: Mosque
          required: false
        - label: Geyser
          required: false
        - label: Causeway
          required: false
        - label: Monument
          required: false
