name: Transform the image (medium)
title: Game medium - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Fortress
          required: false
        - label: Statue
          required: false
        - label: Pier
          required: false
        - label: Dock
          required: false
        - label: Cityscape
          required: false
        - label: Volcano
          required: false
        - label: Church
          required: false
