name: Transform the image (medium)
title: Game medium - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Deck
          required: false
        - label: Orchard
          required: false
        - label: Mosque
          required: false
        - label: Plaza
          required: false
        - label: Parkway
          required: false
        - label: Fountain
          required: false
        - label: Road
          required: false
