name: Transform the image (medium)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: can
          required: false
        - label: works
          required: false
        - label: so
          required: false
        - label: we
          required: false
        - label: interesting
          required: false
        - label: for
          required: false
        - label: it
          required: false
