name: Transform the image (medium)
title: Game medium - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Cityscape
          required: false
        - label: Coral
          required: false
        - label: Bicycle
          required: false
        - label: Dock
          required: false
        - label: Vineyard
          required: false
        - label: Thoroughfare
          required: false
        - label: Plain
          required: false
