name: Transform the image (medium)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Thoroughfare
          required: false
        - label: Veranda
          required: false
        - label: Bicycle
          required: false
        - label: Rainforest
          required: false
        - label: Statue
          required: false
        - label: Archipelago
          required: false
        - label: Gulf
          required: false
