name: Transform the image (medium)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Patio
          required: false
        - label: Swamp
          required: false
        - label: Arena
          required: false
        - label: Lane
          required: false
        - label: Tower
          required: false
        - label: Lift
          required: false
        - label: Road
          required: false
