name: Transform the image (medium)
title: Game medium - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Labyrinth
          required: false
        - label: Temple
          required: false
        - label: Road
          required: false
        - label: Arena
          required: false
        - label: Field
          required: false
        - label: Fireplace
          required: false
        - label: Tree
          required: false
