name: Transform the image (medium)
title: Game medium - do not change the title just fill out the form
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Esplanade
          required: false
        - label: Plane
          required: false
        - label: Cloud
          required: false
        - label: Porch
          required: false
        - label: Boulevard
          required: false
        - label: Bluff
          required: false
        - label: Lift
          required: false
