name: Transform the image (medium)
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Archipelago
          required: false
        - label: Palace
          required: false
        - label: Savannah
          required: false
        - label: Grotto
          required: false
        - label: Alcove
          required: false
        - label: Forest
          required: false
        - label: Island
          required: false
