name: Create New Image
description: A form to select the options available for a new image creation

body:
  - type: markdown
    attributes:
      value: |
        ### Please select only one of the following:

  - type: dropdown
    id: single-selection
    attributes:
      label: Choose one
      options:
        - Cat
        - Dog
        - Building
        - Tree
        - Flower
        - Book
        - Car
        - Boat
        - Ocean
        - Desert
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:

  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
        - label: Grass
          required: false
        - label: Blue sky
          required: false
        - label: Clouds
          required: false
        - label: Rain
          required: false
        - label: Sun
          required: false
        - label: Foggy
          required: false
        - label: Snow
          required: false
        - label: Sand
          required: false
        - label: Hail
          required: false
        - label: Rainbow
          required: false
        - label: Moon
          required: false
        - label: Stars
          required: false
        
