name: Check Current Winners

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00
  workflow_dispatch:
  workflow_call:

jobs:
  CheckWinners:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for winners
        run: |
          chmod +x ./workflowScripts/check-winners.sh
          ./workflowScripts/check-winners.sh

      - name: Commit and push changes
        run: |
          chmod +x ./workflowScripts/pull-then-push.sh
          ./workflowScripts/pull-then-push.sh

     - name: Print out for validation
        run: |
          echo "The winners have been checked and the changes have been pushed to the repository."
          echo "Please check the repository to verify the changes."
