name: Start New Game

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00
  workflow_dispatch:
    inputs:
      targetURL:
        description: 'The URL of the image to be targeting for transformation'
        required: true
        default: 'https://fileserver.matissetec.dev/output/similarImages/630649313860780043/6166500929/6166500929/png'
      topic:
        description: 'The topic of the target image'
        required: true
        default: 'A beautiful landscape with a river'

jobs:
  NewGameCreation:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Word Lists with Difficulty-Based Probability
        run: |
          chmod +x ./workflowScripts/generate-word-list.sh
          ./workflowScripts/generate-word-list.sh
        env:
          WORD_LIST: ${{ vars.WORD_LIST }}

      - name: Clear the current votes
        run: |
          chmod +x ./workflowScripts/reset-game-values.sh
          ./workflowScripts/reset-game-values.sh
        env:
          TARGET_URL: ${{ inputs.targetURL }}

      - name: Set Game Information Readme
        run: |
          chmod +x ./workflowScripts/generate-game-info.sh
          ./workflowScripts/generate-game-info.sh
        env:
          TARGET_URL: ${{ inputs.targetURL }}
          TOPIC: ${{ inputs.topic }}
      
      - name: Save topic for later use
        run: echo ${{ inputs.topic }} > PlayGame/currentTopic.txt

      - name: Commit changes
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        run: |
          chmod +x pull-then-push.sh
          ./workflowScripts/pull-then-push.sh   
