name: Update Game

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00
  workflow_dispatch:

jobs:
  UpdateGame:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Workflow File
        env:
          CURRENT_WORD_LIST: ${{ vars.CURRENT_WORD_LIST }}
        run: |
          # Convert comma-delimited list into YAML formatted options
          NEW_OPTIONS=$(echo "${CURRENT_WORD_LIST}" | awk -F, '{for(i=1;i<=NF;i++) printf "        - label: %s\n          required: false\n", $i}')

          # Create the entire YAML file
          cat <<EOF > .github/ISSUE_TEMPLATE/easy.yml
name: Transform the image
description: A form to select the options available for transforming your current image.

body:
  - type: markdown
    attributes:
      value: |
        ### You can select as many of these as you want:
  - type: checkboxes
    id: multi-selection
    attributes:
      label: Choose multiple
      options:
$NEW_OPTIONS
EOF

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/ISSUE_TEMPLATE/easy.yml
          git commit -m "Creating new game setup"
          git push
