name: Update Game

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00
  workflow_dispatch:

jobs:
  UpdateGame:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Workflow File with awk
        env:
          CURRENT_WORD_LIST: ${{ vars.CURRENT_WORD_LIST }}
        run: |
          # Create the entire YAML file using awk
          awk -v options="${CURRENT_WORD_LIST}" 'BEGIN {
            print "name: Transform the image";
            print "description: A form to select the options available for transforming your current image.";
            print "";
            print "body:";
            print "  - type: markdown";
            print "    attributes:";
            print "      value: |";
            print "        ### You can select as many of these as you want:";
            print "  - type: checkboxes";
            print "    id: multi-selection";
            print "    attributes:";
            print "      label: Choose multiple";
            print "      options:";
            split(options, opts, ",");
            for (i in opts) {
              gsub(/^[ \t]+|[ \t]+$/, "", opts[i]);
              print "        - label: " opts[i];
              print "          required: false";
            }
          }' > .github/ISSUE_TEMPLATE/easy.yml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/ISSUE_TEMPLATE/easy.yml
          git commit -m "Creating new game setup"
          git push
