name: Update Game

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00
  workflow_dispatch:

jobs:
  UpdateGame:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete Workflow Options
        run: |
          echo "Modifying workflows..."
          # Remove all options from the workflow file
          sed -i '/options:/,/^    attributes:/d' .github/ISSUE_TEMPLATE/easy.yml
          echo "Workflows modified!"

      - name: Add New Options
        env:
          CURRENT_WORD_LIST: ${{ vars.CURRENT_WORD_LIST }}
        run: |
          # Convert comma-delimited list into YAML formatted options
          NEW_OPTIONS=$(echo "${CURRENT_WORD_LIST}" | awk -F, '{for(i=1;i<=NF;i++) printf "      - label: %s\n        required: false\n", $i}')

          # Insert the new options in the correct location
          awk -v new_options="$NEW_OPTIONS" '
            /id: multi-selection/ {
                print;
                print "    attributes:";
                print "      label: Choose multiple";
                print "    options:";
                print new_options;
                next
            }
            {print}
          ' .github/ISSUE_TEMPLATE/easy.yml > temp.yml
          mv temp.yml .github/ISSUE_TEMPLATE/easy.yml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Creating new game setup"
          git push
